brand:
    title: Jekyll Statuspage
    logo: /assets/icon.jpg

color-scheme: # blue, dark or red (light is default)

site-list:
  links:
    - label: "Main"
      url: "https://forgenst.com"
      text: "Main Website"
    - label: "Portfolio"
      url: "https://eapm.forgenst.com"
    - label: "Blog"
      url: "https://blog.forgenst.com"