brand:
    title: Jekyll Statuspage
    logo: /assets/icon.jpg

color-scheme: # blue, dark or red (light is default)

list-sites:
    - website: "https://forgenst.com"
    - website: "https://eapm.forgenst.com"